### ISSUE TITLE
C# OpenGL

### ISSUE THREAD

**Issue by raffdp** [moethu/webg3n#14]
I have an OpenGL viewport written in C#. Could that be used as the server side render? I suppose the question is as much to do with Golang itself as the project itself.

**Comment by moethu** [comment]
Indeed, you could use a your C# OpenGL Renderer as a Serverside renderer. However the question is does it run on windows only or would it work using mono? If it's windows only it would probably make more sense serving it through ASP or any other MS web solution.

**Comment by raffdp** [comment]
Thanks @moethu for the reply. I think I will probably need to get your version up and going first. Do you have any instructions or pointers? I am not a Go "Pro" ;) I noticed you mention it needs to be on Mono.

**Comment by moethu** [comment]
@damianrafferty mono is for running .NET apps on linux. I understood you want to implement a C# ServerSide Renderer. But I think I misunderstood you. If you want to run the go renderer and embed it into a C# canvas you simply have to use websockets in C# and place the base64 encoded image stream into an image. For building it should be enough to run go build
